// <auto-generated />
using Internshub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Internshub.Migrations.AddInternshipDb
{
    [DbContext(typeof(AddInternshipDbContext))]
    partial class AddInternshipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Internshub.Models.AddInternshipModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("InternshipMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternshipType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Internship_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Internship_Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Internship_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntershipPicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinQualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilites")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Internship");
                });
#pragma warning restore 612, 618
        }
    }
}
